src/SpaceX/urls.py
from django.urls import path,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('launches.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/launches/urls.py
from django.urls import path
from . import views
app_name = 'main'

urlpatterns = [ 
    path('',views.home,name="home"),
    path('launches/',views.allLaunches,name="allLaunches"),
    path('launches/<str:category>/<int:no>',views.launches,name="launches"),
    path('launches/past',views.launchesPast,name="launchesPast"),
    path('launches/upcoming',views.launchesUpcoming,name="launchesUpcoming"),
    path('missions/',views.allMissions,name="allMissions"),
    path('missions/<int:no>',views.missions,name="missions"),
    path('cores/',views.allCores,name="allCores"),
    path('cores/<int:no>',views.cores,name="cores"),
    path('rockets/',views.allRockets,name="allRockets"),
    path('rockets/<int:no>',views.rockets,name="rockets"),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/base.css' %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/home.css' %}" />
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
    
    {% block css %}
    {% endblock css %}
</head>
<body>
    <section id="sidenav">
    {% block sidenav %}
    {% endblock sidenav %}
    </section>
    <main>
        <div class="info-window">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
</body>
{% block scripts %}
{% endblock scripts %}
</html>

src/templates/cores.html
{% extends 'cores_base.html' %}
{% load static %}
{% block content %}
    <header id="main">
        <div class="title"><h2>{{current.mission_name}}</h2>
        </div>
    <div class="launchdate"><h4>
    {{current.launch_date}}</h4>
    </div>
    </header>
<div class="wrapper">
<div></div>
    </div>
    <div class="info-class"><h4>Mission Flight</h4> {{ current.mission_flight }}</div><br>
    <div class="info-class"><h4>Core Serial</h4> {{ current.core_serial}}</div><br>
    <div class="desc">
        {% if current.details != None %}
        {{current.details}}
        {% else %}
        No description provided.
        {% endif %}
    </div>
{% endblock content %}

src/templates/cores_base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Launches
{% endblock title %}


{% block css %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/launches.css' %}" />
{% endblock css %}
    
{% block sidenav %}
<div class="nav">
    <img class="menu-icon" src="{% static '/images/menu-icon.svg' %}">
<nav>
<section id="category-container">
    <a href="{% url 'main:home' %}"><div class="sec">Welcome to</div>
    <div class="pri">Space X</div></a>
        <p>Categories</p>
        <section id="categories">
            <a href="{% url 'main:allLaunches' %}"><div class="category"><img class=" pink" src="{% static 'images/launch-icon.svg' %}">Launches</div></a>
            <a href="{% url 'main:allRockets' %}"><div class="category"><img class=" blue" src="{% static 'images/rocket-icon.svg' %}">Rockets</div></a>
            <a href="{% url 'main:allCores' %}"><div class="category "><img class="purple" src="{% static 'images/core-icon.svg' %}">Cores</div></a>
            <a href="{% url 'main:allMissions' %}"><div class="category"><img class=" teal" src="{% static 'images/mission-icon.svg' %}">Missions</div></a>
        </section>
    </section>
</nav>
<section id="list">
<div class="list">
<div class="maintitle">
    <div>
<h1>Cores</h1></div>
    <div><form action="{% url 'main:cores' no=no %}" method="POST">
        {% csrf_token %} 
        <button id="refresh" name="refresh" class="button" type="submit"><ion-icon name="refresh"></ion-icon></button>
    </form></div>
    </div>
<div id="outer" class = "outer">
<div id="head" class="col1">Core Serial</div>
<div id="head" class="col2">Mission Name</div>
</div>
<div class="table">
{% for core in core_details %}
    <div class = "outer {% if no == core.id %}selected{% endif %}">
    <a href="{% url 'main:cores' no=core.id %}">
    <div class="col1">{{core.core_serial}}</div>
    <div class="col2">{{core.mission_name}}</div>
    </a></div>
{% endfor %}
</div>
</div>

</section>
</div>
{% endblock sidenav %} 
{% block content %}
{% endblock content %} 

{% block scripts %}
<script>
        (function() {
            var menu = document.querySelector('nav'),
            list = document.getElementById('list'),
                menulink = document.querySelector('.menu-icon');
        
            menulink.addEventListener('click',function(e) {
                menu.classList.toggle('active');
                    e.preventDefault();
                list.classList.toggle('disable');
                    e.preventDefault();
            });
        })();
</script>
{% endblock scripts %}

src/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Launches
{% endblock title %}


{% block css %}
{% endblock css %}
    
{% block sidenav %}

<section id="category-container">
    <a href="{% url 'main:home' %}"><div class="sec">Welcome to</div>
    <div class="pri">Space X</div></a>
        <p>Categories</p>
        <section id="categories">
            <a href="{% url 'main:allLaunches' %}"><div class="category"><img class=" pink" src="{% static 'images/launch-icon.svg' %}">Launches</div></a>
            <a href="{% url 'main:allRockets' %}"><div class="category"><img class=" blue" src="{% static 'images/rocket-icon.svg' %}">Rockets</div></a>
            <a href="{% url 'main:allCores' %}"><div class="category "><img class="purple" src="{% static 'images/core-icon.svg' %}">Cores</div></a>
            <a href="{% url 'main:allMissions' %}"><div class="category"><img class=" teal" src="{% static 'images/mission-icon.svg' %}">Missions</div></a>
        </section>
    </section>
{% endblock sidenav %}  
{% block content %}
    <header>
        <h2>Latest Launch</h2>
        <h4>
            {{latest.launch_date}}
        </h4>
    </header>
    <div class="wrapper">
        <div class="title">
            <h3>
                {{latest.rocket_name}}
            </h3>
            {% if latest.launch_success == "True" %}
            <div class="success">Success</div>
            {% else %}
            <div class="failure">Failed</div>
            {% endif %}
        </div>
        <div class="links">
            <a target="_blank" href="{{latest.reddit_launch}}"><ion-icon name="logo-reddit"></ion-icon></a>
            <a target="_blank" href="{{latest.video_link}}"><ion-icon name="logo-youtube"></ion-icon></a>
            <a target="_blank" href="{{latest.article_link}}"><ion-icon name="laptop"></ion-icon></a>
        </div>
    </div>
    <div class="info-class"><h4>Flight No</h4> {{ latest.flight_number }}</div>
    <div class="desc">
        {{latest.details}}
    {% if current.wikipedia != None %}
    <a target="_blank" href="{{latest.wikipedia}}"><button class="read">Read more</button></a>{% endif %}
    </div>
    <header>
        <h2>Upcoming Launch</h2>
        <h4>
            {{next.launch_date}}
        </h4>
    </header>
    <div class="outer">
        <div class="title">
            <h3>
                {{next.rocket_name}}
            </h3>
        </div>
        <div class="links">
        
            {% if next.reddit_launch != None %}
            <a target="_blank" href="{{next.reddit_launch}}"><ion-icon name="logo-reddit"></ion-icon></a>
            {% endif %}
            {% if next.video_link != None %}
            <a target="_blank" href="{{next.video_link}}"><ion-icon name="logo-youtube"></ion-icon></a>
            {% endif %}
            {% if next.article_link != None %}
            <a target="_blank" href="{{next.article_link}}"><ion-icon name="laptop"></ion-icon></a>
            {% endif %}
        </div>
    </div>
    <div class="info-class"><h4>Flight No</h4> {{ next.flight_number }}</div>
    <div class="desc">
        {{next.details}}
    {% if next.wikipedia != None %}
    <a target="_blank" href="{{next.wikipedia}}"><button class="read">Read more</button></a>{% endif %}
    </div>
{% endblock content %}

src/templates/launches.html
{% extends 'launches_base.html' %}
{% load static %}
{% block content %}
    <header>
        <div class="title"><h2>{{current.rocket_name}}</h2>
        {% if current.launch_success == None %}
            <div class="upcoming">Upcoming</div>
        {% elif current.launch_success == "True" %}
            <div class="success">Success</div>
        {% else %}
            <div class="failure">Failed</div>
        {% endif %}
        </div>
        <h4>
            {{current.launch_date}}
        </h4>
    </header>
<div class="wrapper">
<div></div>
        <div class="links">
        
            {% if current.reddit_launch != None %}
            <a target="_blank" href="{{current.reddit_launch}}"><ion-icon name="logo-reddit"></ion-icon></a>
            {% endif %}
            {% if current.video_link != None %}
            <a target="_blank" href="{{current.video_link}}"><ion-icon name="logo-youtube"></ion-icon></a>
            {% endif %}
            {% if current.article_link != None %}
            <a target="_blank" href="{{current.article_link}}"><ion-icon name="laptop"></ion-icon></a>
            {% endif %}
        </div>
    </div>
    <div class="info-class"><h4>Flight No</h4> {{ current.flight_number }}</div><br>
    <div class="main-info">
    <div>
    <div class="desc">
        {% if current.details != None %}
        {{current.details}}
        {% else %}
        No description available.
        {% endif %}
    </div>
    {% if current.wikipedia != None %}
    <a target="_blank" href="{{current.wikipedia}}"><button class="read">Read more</button></a>{% endif %}</div>
    {% if current.mission_patch_link != None %}<div class="patch"><img src="{{current.mission_patch_link}}"<br>Mission patch</div>{% endif %}
    </div>
{% endblock content %}

src/templates/launches_base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Launches
{% endblock title %}


{% block css %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/launches.css' %}" />
{% endblock css %}
    
{% block sidenav %}
<div class="nav">
    <img class="menu-icon" src="{% static '/images/menu-icon.svg' %}">
<nav>
<section id="category-container">
    <a href="{% url 'main:home' %}"><div class="sec">Welcome to</div>
    <div class="pri">Space X</div></a>
        <p>Categories</p>
        <section id="categories">
            <a href="{% url 'main:allLaunches' %}"><div class="category"><img class=" pink" src="{% static 'images/launch-icon.svg' %}">Launches</div></a>
            <a href="{% url 'main:allRockets' %}"><div class="category"><img class=" blue" src="{% static 'images/rocket-icon.svg' %}">Rockets</div></a>
            <a href="{% url 'main:allCores' %}"><div class="category "><img class="purple" src="{% static 'images/core-icon.svg' %}">Cores</div></a>
            <a href="{% url 'main:allMissions' %}"><div class="category"><img class=" teal" src="{% static 'images/mission-icon.svg' %}">Missions</div></a>
        </section>
    </section>
</nav>
<section id="list">
<div class="list">
<div class="maintitle">
    <div><h1>{{category|title}} Launches</h1></div>
    <div><form action="{% url 'main:launches' no=no category=category %}" method="POST">
        {% csrf_token %} 
        <button id="refresh" name="refresh" class="button" type="submit"><ion-icon name="refresh"></ion-icon></button>
    </form></div>
</div><div class="filter">Filter
<form id="filter" method="POST">
{% csrf_token %} 
<select  class = "options" name="category">
    <option {% if category == "upcoming" %} selected {% endif %}value="upcoming">Upcoming</option>
    <option {% if category == "past" %} selected {% endif %} value="past">Past</option>
    <option {% if category == "all" %} selected {% endif %} value="all">All</option>
    <input name="filter" class="button" type="submit" value="Filter">
</select>
</form> 
</div>
<div id="outer" class = "outer">
<div id="head" class="col1">Flight No.</div>
<div id="head" class="col2">Rocket Name</div>
</div>
<div class="table">
{% for launch in launch_details %}
    <div class = "outer {% if launch.id == no %}selected{% endif %}">
    <a href="{% url 'main:launches' no=launch.id category=category %}">
    <div class="col1">{{launch.flight_number}}</div>
    <div class="col2">{{launch.rocket_name}}</div>
    </a></div>
{% endfor %}
</div>
</div>

</section>
</div>
{% endblock sidenav %} 
{% block content %}
{% endblock content %} 

{% block scripts %}
<script>
        (function() {
            var menu = document.querySelector('nav'),
            list = document.getElementById('list'),
                menulink = document.querySelector('.menu-icon');
        
            menulink.addEventListener('click',function(e) {
                menu.classList.toggle('active');
                    e.preventDefault();
                list.classList.toggle('disable');
                    e.preventDefault();
            });
        })();
</script>
{% endblock scripts %}

src/templates/missions.html
{% extends 'missions_base.html' %}
{% load static %}
{% block content %}
    <header>
        <div class="title"><h2>{{current.mission_name}}</h2>
    </header>
<div class="wrapper">
<div></div>
        <div class="links">
        
            {% if current.twitter != None %}
            <a target="_blank" href="{{current.twitter}}"><ion-icon name="logo-twitter"></ion-icon></a>
            {% endif %}
            {% if current.website != None %}
            <a target="_blank" href="{{current.website}}"><ion-icon name="laptop"></ion-icon></a>
            {% endif %}
        </div>
    </div>
    <div class="info-class"><h4>Mission ID</h4> {{ current.mission_id }}</div><br>
    <div class="desc">
        {% if current.description != None %}
        {{current.description}}
        {% else %}
        No description provided.
        {% endif %}
    </div>
    {% if current.wikipedia != None %}
    <a target="_blank" href="{{current.wikipedia}}"><button class="read">Read more</button></a>{% endif %}
{% endblock content %}

src/templates/missions_base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Launches
{% endblock title %}


{% block css %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/launches.css' %}" />
{% endblock css %}
    
{% block sidenav %}
<div class="nav">
    <img class="menu-icon" src="{% static '/images/menu-icon.svg' %}">
<nav>
<section id="category-container">
    <a href="{% url 'main:home' %}"><div class="sec">Welcome to</div>
    <div class="pri">Space X</div></a>
        <p>Categories</p>
        <section id="categories">
            <a href="{% url 'main:allLaunches' %}"><div class="category"><img class=" pink" src="{% static 'images/launch-icon.svg' %}">Launches</div></a>
            <a href="{% url 'main:allRockets' %}"><div class="category"><img class=" blue" src="{% static 'images/rocket-icon.svg' %}">Rockets</div></a>
            <a href="{% url 'main:allCores' %}"><div class="category "><img class="purple" src="{% static 'images/core-icon.svg' %}">Cores</div></a>
            <a href="{% url 'main:allMissions' %}"><div class="category"><img class=" teal" src="{% static 'images/mission-icon.svg' %}">Missions</div></a>
        </section>
    </section>
</nav>
<section id="list">
<div class="list">
<div class="maintitle">
    <div>
<h1>Missions</h1></div>
    <div><form action="{% url 'main:missions' no=no %}" method="POST">
        {% csrf_token %} 
        <button id="refresh" name="refresh" class="button" type="submit"><ion-icon name="refresh"></ion-icon></button>
    </form></div>
    </div>
<div id="outer" class = "outer">
<div id="head" class="col1">Mission ID</div>
<div id="head" class="col2">Mission Name</div>
</div>
<div class="table">
{% for mission in mission_details %}
    <div class = "outer {% if no == mission.id %}selected{% endif %}">
    <a href="{% url 'main:missions' no=mission.id %}">
    <div class="col1">{{mission.mission_id}}</div>
    <div class="col2">{{mission.mission_name}}</div>
    </a></div>
{% endfor %}
</div>
</div>

</section>
</div>
{% endblock sidenav %} 
{% block content %}
{% endblock content %} 

{% block scripts %}
<script>
        (function() {
            var menu = document.querySelector('nav'),
            list = document.getElementById('list'),
                menulink = document.querySelector('.menu-icon');
        
            menulink.addEventListener('click',function(e) {
                menu.classList.toggle('active');
                    e.preventDefault();
                list.classList.toggle('disable');
                    e.preventDefault();
            });
        })();
</script>
{% endblock scripts %}

src/templates/rockets.html
{% extends 'rockets_base.html' %}
{% load static %}
{% block content %}
    <header>
        <div class="title"><h2>{{current.rocket_name}}</h2>
        {% if current.active == "True" %}
            <div class="success">Active</div>
        {% else %}
            <div class="failure">Inactive</div>
        {% endif %}
        </div>
        <h4>
            {{current.first_flight}}
        </h4>
    </header>
<div class="wrapper">
<div></div>
        <div class="links">
        
            {% if current.reddit_launch != None %}
            <a target="_blank" href="{{current.reddit_launch}}"><ion-icon name="logo-reddit"></ion-icon></a>
            {% endif %}
            {% if current.video_link != None %}
            <a target="_blank" href="{{current.video_link}}"><ion-icon name="logo-youtube"></ion-icon></a>
            {% endif %}
            {% if current.article_link != None %}
            <a target="_blank" href="{{current.article_link}}"><ion-icon name="laptop"></ion-icon></a>
            {% endif %}
        </div>
    </div>
    <div class="info-class"><h4>ID</h4> {{ current.rocket_number }}</div><br>
    <div class="info-class"><h4>Country</h4> {{ current.country }}</div><br>
    <div class="info-class"><h4>Cost/launch</h4> ${{ current.cost_per_launch }}</div><br>
    <div class="main-info">
    <div>
    <div class="desc">
        {% if current.description != None %}
        {{current.description}}
        {% else %}
        No description available.
        {% endif %}
    </div>
    {% if current.wikipedia != None %}
    <a target="_blank" href="{{current.wikipedia}}"><button class="read">Read more</button></a>{% endif %}</div>
    {% if current.mission_patch_link != None %}<div class="patch"><img src="{{current.mission_patch_link}}"<br>Mission patch</div>{% endif %}
    </div>
{% endblock content %}

src/templates/rockets_base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Rockets
{% endblock title %}


{% block css %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/launches.css' %}" />
{% endblock css %}
    
{% block sidenav %}
<div class="nav">
    <img class="menu-icon" src="{% static '/images/menu-icon.svg' %}">
<nav>
<section id="category-container">
    <a href="{% url 'main:home' %}"><div class="sec">Welcome to</div>
    <div class="pri">Space X</div></a>
        <p>Categories</p>
        <section id="categories">
            <a href="{% url 'main:allLaunches' %}"><div class="category"><img class=" pink" src="{% static 'images/launch-icon.svg' %}">Launches</div></a>
            <a href="{% url 'main:allRockets' %}"><div class="category"><img class=" blue" src="{% static 'images/rocket-icon.svg' %}">Rockets</div></a>
            <a href="{% url 'main:allCores' %}"><div class="category "><img class="purple" src="{% static 'images/core-icon.svg' %}">Cores</div></a>
            <a href="{% url 'main:allMissions' %}"><div class="category"><img class=" teal" src="{% static 'images/mission-icon.svg' %}">Missions</div></a>
        </section>
    </section>
</nav>
<section id="list">
<div class="list">
<div class="maintitle">
    <div><h1>Rockets</h1></div>
    <div><form action="{% url 'main:rockets' no=no %}" method="POST">
        {% csrf_token %} 
        <button id="refresh" name="refresh" class="button" type="submit"><ion-icon name="refresh"></ion-icon></button>
    </form></div>
</div>
<div id="outer" class = "outer">
<div id="head" class="col1">ID</div>
<div id="head" class="col2">Rocket Name</div>
</div>
<div class="table">
{% for rockets in rocket_details %}
    <div class = "outer {% if rockets.id == no %}selected{% endif %}">
    <a href="{% url 'main:rockets' no=rockets.id %}">
    <div class="col1">{{rockets.rocket_number}}</div>
    <div class="col2">{{rockets.rocket_name}}</div>
    </a></div>
{% endfor %}
</div>
</div>

</section>
</div>
{% endblock sidenav %} 
{% block content %}
{% endblock content %} 

{% block scripts %}
<script>
        (function() {
            var menu = document.querySelector('nav'),
            list = document.getElementById('list'),
                menulink = document.querySelector('.menu-icon');
        
            menulink.addEventListener('click',function(e) {
                menu.classList.toggle('active');
                    e.preventDefault();
                list.classList.toggle('disable');
                    e.preventDefault();
            });
        })();
</script>
{% endblock scripts %}